---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-ubuntu
spec:
  containers:
  - name: nginx-ubuntu
    image: https://index.docker.io/v1/skbskhanin/ubuntu_2204:202404090035
      #    imagePullPolicy: Always
    ports:
    - containerPort: 8080
      protocol: TCP
  imagePullSecrets:
  - name: regcred
