---
apiVersion: v1
kind: Pod
metadata:
    name: nginx-ubuntu
spec:
    containers:
    - image: skbskhanin/ubuntu_2204
      tag : 202404090035
      name: nginx-ubuntu
      ports:
      - containerPort: 8080
        protocol: TCP

